jkdk:
  username: ************
  password: ************
  from: ************
  to: ************
spring:
  mail:
    host: ************
    username: ************
    password: ************
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
server:
  port: 10087
